name: Build Plugin

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        set -o pipefail
        mvn -B -e -Dmaven.test.skip=true clean package | tee build.log
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: realistic highlands2
        path: target/*.jar
    
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: build.log
